### ISSUE TITLE
What about TINC?

### ISSUE THREAD

**Issue by brammittendorff** [jedisct1/dsvpn#16]
In the README.md you note a few vpn servers & clients but I do not hear you about tinc, is there a reason for that? Because it is possible to use `TCPOnly = yes` and set the port to the desired port you want. It is ofc a little bit bigger: `488K` but I do not see you mention tinc and I was wondering why?

**Comment by jedisct1** [comment]
[Scary security track record](https://www.tinc-vpn.org/security/), requires OpenSSL (which instantaneously makes it bigger), too much documentation to read in order to get started.

That [VTUN fork](https://github.com/jedisct1/vtun) is similar to TINC and might be a bit more secure, but would still have been overkill.
