### ISSUE TITLE
Add iOS and Android Client

### ISSUE THREAD

**Issue by yeluolei** [jedisct1/dsvpn#18]
I am pretty sure we need this. but don't know how to build it. I am not an network expert.

**Comment by jedisct1** [comment]
It doesn't work on iOS and Android, because VPNs work differently on these iOS and Android than other operating systems.

The code is small and simple, so it shouldn't be too difficult for someone familiar with iOS and Android, but I don't have much experience with developing on these platforms.

**Comment by cute** [comment]
@yeluolei 

I have did it in my iOS app test version. if you want to try it, i can send you an invitation.

**Comment by jedisct1** [comment]
@cute Wow, this is awesome! I'd love to have an invite to test this!

**Comment by cute** [comment]
@jedisct1  

https://testflight.apple.com/join/yQ844iAv

**Comment by emielmolenaar** [comment]
This would be awesome. Thumbs up for the effort.

**Comment by mobiliodevelopment** [comment]
@cute any update on iOS app?

**Comment by jradd** [comment]
@cute 
謝謝你这个看及很好

**Comment by screenzen** [comment]
@cute would much appreciate access to your ios implementation if possible. Thanks!

**Comment by kameneken** [comment]
Hey guys, I am working on an Android app for dsvpn which will soon be released on Google Play for closed testing, it is fully featured with Multipath TCP and TCP Fragmentation. If you're interested, you can send your Google Play account to [kameneken@gmail.com](mailto:kameneken@gmail.com) so that I can send you an invitation to the beta testing.
![Uploading Screenshot_20240417-1605
![Screenshot_20240417-155532](https://github.com/jedisct1/dsvpn/assets/166382900/6812aceb-8224-4121-9aca-4ce0dbffc97b)
![Screenshot_20240417-155511](https://github.com/jedisct1/dsvpn/assets/166382900/f9e2f19b-ec63-4302-ac8d-09f7ad9d11f0)
27.png…]()
