### ISSUE TITLE
witch protocol is used?

### ISSUE THREAD

**Issue by Mehran** [jedisct1/dsvpn#36]
is it Use OPENVPN Protocol ? or same as Wireguard have own Protocol to communicate?

**Comment by jedisct1** [comment]
None of these.

It’s its own, very simple protocol. Unlike these other protocols that have been designed to work over datagrams, dsvpn was explicitly designed to work over TCP, so it can use session-based encryption. 

It isn’t documented yet because it will soon need a breaking change in order for clients to retrieve information (mainly DNS servers) from the server.
