### ISSUE TITLE
DSVPN & Time Capsule

### ISSUE THREAD

**Issue by johnalanwoods** [jedisct1/dsvpn#46]
I'm trying to understand how DSVPN works (and it works very well :) ) - expect one item.

Normally when I use my OpenVPN setup I can see my time capsule on my home local network when I connect to the VPN (as the VPN terminates in my home).

With DSVPN an Arp -a doesn't show any clients on my home network, but I can VNC to my RaspberryPi if I use the local IP that I fetch directly from the Pi.

So the network does seem to work, and seemingly is secure, I was wondering if you could help me understand how I might get devices like the Time Capsule to show under Network in finder? or maybe explain if this isn't possible due to how simple DSVPN is? 

Is there a caveat with regard to connectivity or security when compared with OpenVPN? (assuming XooDoo is safe) I guess not?

**Comment by jedisct1** [comment]
Hi,

You should be able to connect to the Time Capsule with `Connect to server` in the Finder menu.

The reason you are not seeing it in the Finder is that local service discovery is made using mDNS, that sends multicast packets (from/to IP addresses in `224.0.0.0/8`).
In `dsvpn`, these packets stay on the local network because even when using the VPN, I'd rather still see my local devices (printer, phone, etc).

**Comment by johnalanwoods** [comment]
Thank you that worked!

By the way - should this solution look end to end encrypted to the host network admin/ISP?

**Comment by jedisct1** [comment]
Yes, nothing unencrypted will go to the public network, including connections to your Time Capsule.

**Comment by johnalanwoods** [comment]
Thank you Frank.
