### ISSUE TITLE
How can I connect a smart TV client to the DSVPN server

### ISSUE THREAD

**Issue by amitsaxena** [jedisct1/dsvpn#47]
First of all thanks for creating this awesome piece of software! It works great! 👍 ❤️ 

I want to connect my Samsung Smart TV to the VPN server but not sure what's a good way to do it. I cannot install custom software/client on the TV to be able to connect. It does however allow me to change the network settings and set up a custom DNS server for the TV. Can I somehow use that to route the traffic via VPN server?

One possibility is create a hotspot and then route the traffic through some other device's client, but I would like to avoid the extra hop if it's possible. I have a couple of questions:
1) Is there a way to skip authentication on the server side (without shared key) but only allow traffic from specific IP (or IPs)
2) Can I somehow use the TV DNS settings to connect to the VPN server

**Comment by jedisct1** [comment]
Hi Amit,

Unfortunately, you can’t avoid the extra hop. In the network settings, you can configure the default gateway, which is great, but that gateway must be on the local network.

Even if you enter the IP address of a remote server here (which will probably be not possible), this can’t work because regular TCP/IP packets dont store enough information (they can’t store both the server IP and the real destination IP, in order to be properly routed).

The only workaround would be to install software on it, but this is apparently not an option.

So, yeah, the extra hop is required. Or maybe you can install dsvpn on your router.

**Comment by amitsaxena** [comment]
Thank you for the feedback @jedisct1! Sounds good! 👍
