### ISSUE TITLE
DsVPN as a client crashes Gnome

### ISSUE THREAD

**Issue by linuxundich** [jedisct1/dsvpn#58]
I'm experimenting with dsvpn 0.1.3 on different systems, a laptop and a desktop computer. Usually on Arch Linux with (currently) Gnome 3.34 as desktop environment. Inside a bridged virtualbox I run Ubuntu 19.04 as a control.

I can run dsvpn on both systems with Arch Linux as a server without a problem. The server starts up, and it can receive connections. When I use the Ubuntu-VM as a client, the connection is stable. The problem starts with both Gnome systems.

After a short moment both systems crash completely. Mouse and keyboard don't work anymore. The systems don't answer ssh logins or pings. On the laptop (Dell XPS 15 9570) the caps lock led starts flashing. I have to pull the plug to restart the systems. I'm not sure, what's going on there.

**Comment by jedisct1** [comment]
Unless you got a funny version with a built-in keylogger, `dsvpn` never accesses the keyboard or mouse, and doesn't know anything about Gnome either.

Maybe Gnome is trying to change network settings or firewall rules and acts weird if something is already in place?

Unfortunately, the root cause is likely to be unrelated to `dsvpn` so I doubt anyone would be able to help besides yourself.

Try to find all the steps happening when Gnome start, in order to pinpoint what exact command or step causes the system to freeze. The Ubuntu forums are probably a better place to get help with this very specific issue.
