### ISSUE TITLE
Weird behaviour when connecting from domestic internet service

### ISSUE THREAD

**Issue by johnalanwoods** [jedisct1/dsvpn#66]
I love DSVPN, it's a really handy and lightweight tool.

It works well when connect from a public internet point (generally using 172. or 10. local addresses).

However over the Christmas I was trying too use it **from** a more regular domestic setup (192.) back to my regular setup domestic network (also 192.) it doesn't work.

I can connect successfully, however when trying to access my routers web config page on 192.168.0.1, I instead end up loading the router web config page locally.

I guess it's because both my router and the local router are both 192.168.0.1, however I noticed I can't access any other devices on my home network either.

Is this expected behaviour?

**Comment by jedisct1** [comment]
Hi John,

By default, the routing rules dsvpn installs prevent traffic for the local network from going through the VPN. So that even when you are connected, you can still see your local devices, network volumes, airdrop still works, etc.

If the remote network uses the same subnet as the local one, packets for that subnet will stay on your local network.

The routing/firewall rules can be changed in `src/os.c`.

An alternative is to add additional routes for the devices you want to force route through the VPN.

For example on MacOS:

```sh
sudo route add 192.168.0.1 192.168.192.254
```

Forces packets for `192.168.0.1` to go through `192.168.192.254` (the server VPN IP address).

**Comment by johnalanwoods** [comment]
Hi Frank, makes perfect sense. Thank you.

Closing as non-issue.
