### ISSUE TITLE
compatibility with Asuswrt-Merlin

### ISSUE THREAD

**Issue by cofyc** [jedisct1/dsvpn#72]
hi,

I was trying to compile dsvpn on my router (Asuswrt-Merlin, 384.14_2) and it does not contain any linux headers and `SYS_getrandom` is not defined in headers of GCC either which is installed by [`opkg`](https://github.com/Entware/Entware) (package manager on Asuswrt-Merlin). So I need to define it manually:

```
opkg install gcc
make CC=gcc OPTFLAGS="-DSYS_getrandom=278"
```

Maybe we can define it if the arch is arm64, like this:

```
+++ b/src/charm.c
@@ -328,6 +328,9 @@ void uc_memzero(void *buf, size_t len)
 void uc_randombytes_buf(void *buf, size_t len)
 {
 #ifdef __linux__
+#if defined(__aarch64__) && !defined(SYS_getrandom)
+#define SYS_getrandom 278
+#endif
     if ((size_t) syscall(SYS_getrandom, buf, (int) len, 0) != len) {
         abort();
     }

```

What do you think?

**Comment by jedisct1** [comment]
Hi!

Doesn't a package with linux headers exist at all? It seems a little bit weird, because without these, kernel modules cannot be compiled.

`SYS_getrandom` currently is `318` on `x86_64`, `355` on `x86`, `278` on `aarch64`, `384` on arm32, `359` on PPC... It's a little bit of a mess, and if we want to redefine that macro, it doesn't make sense to do it just for one architecture.

I'd rather avoid adding hacks for uncommon environments. Or maybe `SYS_getrandom` can be tested for and defined in the `Makefile`, but it would be better if the source code itself keeps assuming a modern and sane environment.

**Comment by cofyc** [comment]
no, In gcc headers, `SYS_getrandom` is defined to `__NR_getrandom`. However, it does not ship linux headers. 

```
admin@RT-AC86U-A018:/tmp/home/root# grep '__NR_getrandom' /usr/include/ -R
admin@RT-AC86U-A018:/tmp/home/root# find /usr/include/ -name '*.h'
/usr/include/iperf_api.h
admin@RT-AC86U-A018:/tmp/home/root#
```

I agree the source code itself should keep assuming a modern and sane environment. We can add dirty hacks in Makefile. I opened a PR for this: https://github.com/jedisct1/dsvpn/pull/73
