### ISSUE TITLE
High Latency

### ISSUE THREAD

**Issue by Bestle** [jedisct1/dsvpn#75]
I am currently using DSVPN through openmptcprouter to tunnel my UDP traffic to a VPS.

I have noticed that compared to using Glorytun for the same purpose, I have about 50ms of extra latency, is this sort of thing to be expected?

Neither the router nor VPS are anywhere close to being overloaded and overall bandwidth is comparable.

**Comment by jedisct1** [comment]
On Linux, `dsvpn` uses quick acks, but doesn't disable the Nagle algorithm. It means that if very small packets have to be sent, instead of being sent immediately but one by one, they will be sent together.

This improves usage of network resources, improves reliability on lossy networks, and generally the recommended choice.

The flipside is that `ping` command may show additional latency, but the VPN was optimized for actual applications, not for the`ping` command :) Games may be impacted, but using a VPS is the last thing a gamer would do :)

**Comment by Bestle** [comment]
I use a VPN for _all traffic_ as it's on my router. Is there any way for me to change this behaviour?
